baseurl = "https://rockstar2514.github.io"
title = "rockstar2514"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Dawood Bin Mansoor"
    info = "Undergraduate Student in the Department of Aerospace Engineering at Indian Institute of Technology, Kanpr."
    description = "Personal Blog"
    keywords = "blog,developer,personal"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "Enter a text here."
    colorscheme = "light"
    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/rockstar2514/"
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
